// Generated by `npm run types` from the linked Supabase project. Do not edit:
// the next run overwrites it. Regenerate after every migration.
//
// It types `supabase.from(...)` and `supabase.rpc(...)` against the real
// schema, which is what stops a hand-written shape drifting from the database
// at build time. The six RPCs that return `jsonb` come back as `Json` here and
// cannot be otherwise -- those are checked at runtime instead; see
// lib/rpcSchemas.ts.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.5'
  }
  public: {
    Tables: {
      ballots: {
        Row: {
          id: string
          poll_id: string
          revised_at: string | null
          submitted_at: string
          voter_id: string | null
          voter_key: string | null
          voter_name: string | null
        }
        Insert: {
          id?: string
          poll_id: string
          revised_at?: string | null
          submitted_at?: string
          voter_id?: string | null
          voter_key?: string | null
          voter_name?: string | null
        }
        Update: {
          id?: string
          poll_id?: string
          revised_at?: string | null
          submitted_at?: string
          voter_id?: string | null
          voter_key?: string | null
          voter_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'ballots_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: false
            referencedRelation: 'polls'
            referencedColumns: ['id']
          },
        ]
      }
      candidates: {
        Row: {
          description: string | null
          id: string
          name: string
          poll_id: string
          sort_order: number
        }
        Insert: {
          description?: string | null
          id?: string
          name: string
          poll_id: string
          sort_order?: number
        }
        Update: {
          description?: string | null
          id?: string
          name?: string
          poll_id?: string
          sort_order?: number
        }
        Relationships: [
          {
            foreignKeyName: 'candidates_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: false
            referencedRelation: 'polls'
            referencedColumns: ['id']
          },
        ]
      }
      invited_voters: {
        Row: {
          email: string
          id: string
          poll_id: string
        }
        Insert: {
          email: string
          id?: string
          poll_id: string
        }
        Update: {
          email?: string
          id?: string
          poll_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'invited_voters_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: false
            referencedRelation: 'polls'
            referencedColumns: ['id']
          },
        ]
      }
      option_confirmations: {
        Row: {
          confirmed_at: string
          id: string
          poll_id: string
          voter_id: string | null
          voter_key: string | null
          voter_name: string | null
        }
        Insert: {
          confirmed_at?: string
          id?: string
          poll_id: string
          voter_id?: string | null
          voter_key?: string | null
          voter_name?: string | null
        }
        Update: {
          confirmed_at?: string
          id?: string
          poll_id?: string
          voter_id?: string | null
          voter_key?: string | null
          voter_name?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'option_confirmations_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: false
            referencedRelation: 'polls'
            referencedColumns: ['id']
          },
        ]
      }
      polls: {
        Row: {
          closed_at: string | null
          created_at: string
          created_by: string
          created_by_email: string
          description: string | null
          group_id: string | null
          id: string
          mode: string
          options_finalized_at: string | null
          question_position: number | null
          question_title: string | null
          show_ballots: boolean
          show_voters: boolean
          solicit_options: boolean
          title: string
          winner_name: string | null
          winner_settled_at: string | null
        }
        Insert: {
          closed_at?: string | null
          created_at?: string
          created_by: string
          created_by_email?: string
          description?: string | null
          group_id?: string | null
          id?: string
          mode?: string
          options_finalized_at?: string | null
          question_position?: number | null
          question_title?: string | null
          show_ballots?: boolean
          show_voters?: boolean
          solicit_options?: boolean
          title: string
          winner_name?: string | null
          winner_settled_at?: string | null
        }
        Update: {
          closed_at?: string | null
          created_at?: string
          created_by?: string
          created_by_email?: string
          description?: string | null
          group_id?: string | null
          id?: string
          mode?: string
          options_finalized_at?: string | null
          question_position?: number | null
          question_title?: string | null
          show_ballots?: boolean
          show_voters?: boolean
          solicit_options?: boolean
          title?: string
          winner_name?: string | null
          winner_settled_at?: string | null
        }
        Relationships: []
      }
      results_notices: {
        Row: {
          poll_id: string
          sent_at: string
        }
        Insert: {
          poll_id: string
          sent_at?: string
        }
        Update: {
          poll_id?: string
          sent_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'results_notices_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: true
            referencedRelation: 'polls'
            referencedColumns: ['id']
          },
        ]
      }
      scores: {
        Row: {
          ballot_id: string
          candidate_id: string
          id: string
          score: number
        }
        Insert: {
          ballot_id: string
          candidate_id: string
          id?: string
          score: number
        }
        Update: {
          ballot_id?: string
          candidate_id?: string
          id?: string
          score?: number
        }
        Relationships: [
          {
            foreignKeyName: 'scores_ballot_id_fkey'
            columns: ['ballot_id']
            isOneToOne: false
            referencedRelation: 'ballots'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'scores_candidate_id_fkey'
            columns: ['candidate_id']
            isOneToOne: false
            referencedRelation: 'candidates'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_suggested_option: {
        Args: {
          p_description: string
          p_name: string
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: undefined
      }
      assert_collecting_options: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: undefined
      }
      assert_open_results_readable: {
        Args: { p_poll_id: string }
        Returns: undefined
      }
      assert_results_readable: {
        Args: { p_poll_id: string }
        Returns: undefined
      }
      ballot_sheet: {
        Args: { p_named: boolean; p_poll_id: string }
        Returns: Json
      }
      broadcast_poll_change: { Args: { p_poll_id: string }; Returns: undefined }
      close_poll: { Args: { p_poll_id: string }; Returns: undefined }
      confirm_options: { Args: { p_poll_id: string }; Returns: undefined }
      confirming_invitee: {
        Args: { p_poll_id: string }
        Returns: {
          closed_at: string | null
          created_at: string
          created_by: string
          created_by_email: string
          description: string | null
          group_id: string | null
          id: string
          mode: string
          options_finalized_at: string | null
          question_position: number | null
          question_title: string | null
          show_ballots: boolean
          show_voters: boolean
          solicit_options: boolean
          title: string
          winner_name: string | null
          winner_settled_at: string | null
        }
        SetofOptions: {
          from: '*'
          to: 'polls'
          isOneToOne: true
          isSetofReturn: false
        }
      }
      create_poll: {
        Args: {
          p_description: string
          p_emails: string[]
          p_mode?: string
          p_option_descriptions?: string[]
          p_options: string[]
          p_show_ballots?: boolean
          p_show_voters?: boolean
          p_solicit_options?: boolean
          p_title: string
        }
        Returns: string
      }
      create_poll_group: {
        Args: {
          p_description: string
          p_emails: string[]
          p_mode?: string
          p_questions: Json
          p_show_ballots?: boolean
          p_show_voters?: boolean
          p_solicit_options?: boolean
          p_title: string
        }
        Returns: string
      }
      creator_add_option: {
        Args: { p_description?: string; p_name: string; p_poll_id: string }
        Returns: undefined
      }
      email_escape: { Args: { p_text: string }; Returns: string }
      finalize_options: { Args: { p_poll_id: string }; Returns: undefined }
      get_poll_ranking: { Args: { p_poll_id: string }; Returns: Json }
      get_poll_results: { Args: { p_poll_id: string }; Returns: Json }
      insert_option: {
        Args: {
          p_description: string
          p_name: string
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: undefined
      }
      insert_poll_row: {
        Args: {
          p_description: string
          p_emails: string[]
          p_group_id?: string
          p_mode: string
          p_options: Json
          p_question_position?: number
          p_question_title: string
          p_show_ballots: boolean
          p_show_voters: boolean
          p_solicit_options: boolean
          p_title: string
        }
        Returns: string
      }
      is_invited_to_poll: { Args: { p_poll_id: string }; Returns: boolean }
      is_poll_creator: { Args: { p_poll_id: string }; Returns: boolean }
      list_polls: {
        Args: { p_limit: number; p_offset: number }
        Returns: {
          closed_at: string
          confirmed_count: number
          created_at: string
          created_by: string
          created_by_email: string
          description: string
          group_id: string
          id: string
          invited_count: number
          is_closed: boolean
          is_complete: boolean
          mode: string
          option_count: number
          options_finalized_at: string
          question_count: number
          question_position: number
          question_title: string
          results_available: boolean
          show_ballots: boolean
          show_voters: boolean
          solicit_options: boolean
          soliciting: boolean
          title: string
          total_count: number
          voted: boolean
          voted_count: number
          winner_name: string
          winner_settled: boolean
        }[]
      }
      normalize_invite_emails: {
        Args: { p_emails: string[] }
        Returns: string[]
      }
      notify_poll_opened: {
        Args: { p_by_itself: boolean; p_poll_id: string }
        Returns: undefined
      }
      notify_results_ready: { Args: { p_poll_id: string }; Returns: undefined }
      open_options_when_all_confirmed: {
        Args: { p_poll_id: string }
        Returns: undefined
      }
      open_poll_ballots: { Args: { p_poll_id: string }; Returns: Json }
      open_poll_confirm_options: {
        Args: { p_poll_id: string; p_voter_key: string; p_voter_name?: string }
        Returns: undefined
      }
      open_poll_group: { Args: { p_poll_id: string }; Returns: Json }
      open_poll_ranking: { Args: { p_poll_id: string }; Returns: Json }
      open_poll_results: { Args: { p_poll_id: string }; Returns: Json }
      open_poll_revise: {
        Args: { p_poll_id: string; p_scores: Json; p_voter_key: string }
        Returns: undefined
      }
      open_poll_submit: {
        Args: {
          p_poll_id: string
          p_scores: Json
          p_voter_key: string
          p_voter_name?: string
        }
        Returns: undefined
      }
      open_poll_suggest_option: {
        Args: { p_description?: string; p_name: string; p_poll_id: string }
        Returns: undefined
      }
      open_poll_unconfirm_options: {
        Args: { p_poll_id: string; p_voter_key: string }
        Returns: undefined
      }
      open_poll_view: {
        Args: { p_poll_id: string; p_voter_key?: string }
        Returns: Json
      }
      options_confirmed_by_everyone: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: boolean
      }
      poll_ballot_scores: { Args: { p_poll_id: string }; Returns: Json }
      poll_ballots: { Args: { p_poll_id: string }; Returns: Json }
      poll_confirmed_count: { Args: { p_poll_id: string }; Returns: number }
      poll_email_audience: {
        Args: {
          p_actor: string
          p_include_creator: boolean
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: string[]
      }
      poll_email_html: {
        Args: { p_body_html: string; p_heading: string; p_link: string }
        Returns: string
      }
      poll_expires_at: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: string
      }
      poll_gate_open: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: boolean
      }
      poll_group: { Args: { p_poll_id: string }; Returns: Json }
      poll_group_members: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: {
          closed_at: string | null
          created_at: string
          created_by: string
          created_by_email: string
          description: string | null
          group_id: string | null
          id: string
          mode: string
          options_finalized_at: string | null
          question_position: number | null
          question_title: string | null
          show_ballots: boolean
          show_voters: boolean
          solicit_options: boolean
          title: string
          winner_name: string | null
          winner_settled_at: string | null
        }[]
        SetofOptions: {
          from: 'polls'
          to: 'polls'
          isOneToOne: false
          isSetofReturn: true
        }
      }
      poll_invite_kind: {
        Args: {
          p_email: string
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: string
      }
      poll_invitees: {
        Args: { p_poll_id: string }
        Returns: {
          email: string
          has_confirmed: boolean
          has_voted: boolean
        }[]
      }
      poll_is_first_question: { Args: { p_poll_id: string }; Returns: boolean }
      poll_page: {
        Args: { p_poll_id: string; p_voter_key?: string }
        Returns: Json
      }
      poll_ranking: { Args: { p_poll_id: string }; Returns: Json }
      poll_results_audience: {
        Args: {
          p_actor: string
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: string[]
      }
      poll_results_ready: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: boolean
      }
      poll_results_revealed: {
        Args: { p_poll: Database['public']['Tables']['polls']['Row'] }
        Returns: boolean
      }
      poll_retention_window: { Args: never; Returns: string }
      poll_status: {
        Args: { p_poll_id: string }
        Returns: {
          confirmed: boolean
          confirmed_count: number
          expires_at: string
          invited: boolean
          invited_count: number
          is_closed: boolean
          is_complete: boolean
          results_available: boolean
          soliciting: boolean
          voted: boolean
          voted_count: number
          winner_name: string
          winner_settled: boolean
        }[]
      }
      poll_tally: { Args: { p_poll_id: string }; Returns: Json }
      poll_winner_name: { Args: { p_poll_id: string }; Returns: string }
      poll_winners: {
        Args: { p_poll_ids: string[] }
        Returns: {
          poll_id: string
          winner_name: string
        }[]
      }
      purge_old_polls: { Args: never; Returns: number }
      replace_scores: {
        Args: { p_ballot_id: string; p_poll_id: string; p_scores: Json }
        Returns: undefined
      }
      reset_poll: { Args: { p_poll_id: string }; Returns: undefined }
      revise_ballot: {
        Args: { p_poll_id: string; p_scores: Json }
        Returns: undefined
      }
      send_poll_email: {
        Args: {
          p_body_html: string
          p_heading: string
          p_poll_id: string
          p_subject: string
          p_to: string
        }
        Returns: undefined
      }
      send_poll_opened_email: {
        Args: {
          p_email: string
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: undefined
      }
      send_results_ready_email: {
        Args: {
          p_email: string
          p_poll: Database['public']['Tables']['polls']['Row']
        }
        Returns: undefined
      }
      settle_winner: { Args: { p_poll_id: string }; Returns: undefined }
      star_round: {
        Args: { p_poll_id: string; p_pool: string[] }
        Returns: Json
      }
      submit_ballot: {
        Args: { p_poll_id: string; p_scores: Json }
        Returns: undefined
      }
      suggest_option: {
        Args: { p_description?: string; p_name: string; p_poll_id: string }
        Returns: undefined
      }
      unconfirm_options: { Args: { p_poll_id: string }; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema['Tables']
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema['Enums']
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema['CompositeTypes']
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
