/**
 * Generated by scripts/sample-poll.sh. Do not edit by hand: change the poll
 * or its ballots in scripts/sample-poll.sql and run that script again.
 *
 * What the public voting page's RPCs answer about the About page's sample
 * poll, recorded against a throwaway database built from the migrations. The
 * tally, the tie-breaks and the full ranking in here are the ones
 * `star_round()` and `poll_ranking()` produced from the ballots in that file;
 * nothing in the browser recomputes them.
 */
import type { SamplePayloads } from './samplePoll'

export const SAMPLE_PAYLOADS: SamplePayloads = {
  'sample-host': {
    view: {
      poll: {
        id: 'sample-host',
        mode: 'open',
        title: 'Movie night',
        group_id: '340edd82-ab8f-bbe4-8a89-c65f8d87c1f8',
        closed_at: null,
        description:
          "A simple sample poll, so you can see what voting looks like. Submitting your vote won't do anything.",
        show_voters: true,
        show_ballots: true,
        question_title: "Who's hosting?",
        solicit_options: false,
        question_position: 1,
      },
      voted: false,
      voters: [],
      options: [
        {
          id: 'cf21e76f-bd55-7bc3-2aa9-ccdf4b469f43',
          name: "Ana's place",
          poll_id: 'sample-host',
          sort_order: 0,
          description: null,
        },
        {
          id: '052db122-d5b8-0bf6-af46-bf8b3295fd0c',
          name: "Ben's loft",
          poll_id: 'sample-host',
          sort_order: 1,
          description: null,
        },
        {
          id: 'e03670fc-7afb-25e2-7cf8-8c8833df9270',
          name: "Chloe's basement",
          poll_id: 'sample-host',
          sort_order: 2,
          description: null,
        },
      ],
      confirmed: false,
      is_closed: false,
      your_name: null,
      soliciting: false,
      voted_count: 0,
      winner_name: null,
      your_scores: null,
      confirmations: [],
      winner_settled: false,
      confirmed_count: 0,
      results_available: false,
      your_confirmed_name: null,
    },
    group: [
      {
        id: 'sample-host',
        question_title: "Who's hosting?",
        question_position: 1,
      },
      {
        id: 'sample-dinner',
        question_title: 'What are we eating?',
        question_position: 2,
      },
      {
        id: 'sample-movie',
        question_title: 'What are we watching?',
        question_position: 3,
      },
    ],
  },
  'sample-movie': {
    view: {
      poll: {
        id: 'sample-movie',
        mode: 'open',
        title: 'Movie night',
        group_id: '340edd82-ab8f-bbe4-8a89-c65f8d87c1f8',
        closed_at: null,
        description:
          "A simple sample poll, so you can see what voting looks like. Submitting your vote won't do anything.",
        show_voters: true,
        show_ballots: true,
        question_title: 'What are we watching?',
        solicit_options: false,
        question_position: 3,
      },
      voted: false,
      voters: [],
      options: [
        {
          id: 'd11848b2-a3e8-f3ca-64c4-e26a6df68d69',
          name: 'Knives Out',
          poll_id: 'sample-movie',
          sort_order: 0,
          description:
            'When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.',
        },
        {
          id: 'e2ebadef-98e8-958d-5afe-b63f4609a8e6',
          name: 'Spirited Away',
          poll_id: 'sample-movie',
          sort_order: 1,
          description:
            "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.",
        },
        {
          id: '652fb1be-f52f-fd5a-6334-9f662e8b06d8',
          name: 'The Matrix',
          poll_id: 'sample-movie',
          sort_order: 2,
          description:
            'A computer hacker discovers that his life is nothing more than an elaborate simulation run by an evil AI.',
        },
        {
          id: 'ef43c5ae-50c3-03cd-8c14-64b05146386c',
          name: 'Paddington 2',
          poll_id: 'sample-movie',
          sort_order: 3,
          description:
            "Paddington, now happily settled with the Brown family and a popular member of the local community, picks up a series of odd jobs to buy the perfect present for his Aunt Lucy's 100th birthday, only for the gift to be stolen.",
        },
        {
          id: '37d6bbad-38b0-2277-0c21-53a78cf0bb06',
          name: 'Mean Girls',
          poll_id: 'sample-movie',
          sort_order: 4,
          description:
            'Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.',
        },
        {
          id: '02e60972-37c3-14cd-31ad-01bb9d14fd78',
          name: 'Honeyland',
          poll_id: 'sample-movie',
          sort_order: 5,
          description:
            'The last female bee-hunter in Europe must save the bees and return the natural balance in Honeyland, when a family of nomadic beekeepers invade her land and threaten her livelihood.',
        },
      ],
      confirmed: false,
      is_closed: false,
      your_name: null,
      soliciting: false,
      voted_count: 0,
      winner_name: null,
      your_scores: null,
      confirmations: [],
      winner_settled: false,
      confirmed_count: 0,
      results_available: false,
      your_confirmed_name: null,
    },
    group: [
      {
        id: 'sample-host',
        question_title: "Who's hosting?",
        question_position: 1,
      },
      {
        id: 'sample-dinner',
        question_title: 'What are we eating?',
        question_position: 2,
      },
      {
        id: 'sample-movie',
        question_title: 'What are we watching?',
        question_position: 3,
      },
    ],
  },
  'sample-dinner': {
    view: {
      poll: {
        id: 'sample-dinner',
        mode: 'open',
        title: 'Movie night',
        group_id: '340edd82-ab8f-bbe4-8a89-c65f8d87c1f8',
        closed_at: null,
        description:
          "A simple sample poll, so you can see what voting looks like. Submitting your vote won't do anything.",
        show_voters: true,
        show_ballots: true,
        question_title: 'What are we eating?',
        solicit_options: false,
        question_position: 2,
      },
      voted: false,
      voters: [],
      options: [
        {
          id: '343e0cd9-9e1f-cf6a-5101-3253a606ffd1',
          name: 'Two big pizzas',
          poll_id: 'sample-dinner',
          sort_order: 0,
          description: 'One pepperoni, one cheese.',
        },
        {
          id: '3ff039b5-b8d6-2e21-1287-53d822ac75e4',
          name: 'Taco bar',
          poll_id: 'sample-dinner',
          sort_order: 1,
          description: 'Build your own tacos!',
        },
        {
          id: '0a7f809d-87fc-6495-6647-d1d9466a9f08',
          name: 'Everyone brings a dish',
          poll_id: 'sample-dinner',
          sort_order: 2,
          description: null,
        },
        {
          id: 'd91bca7c-f67d-9ef3-6a92-574491877abf',
          name: 'Thai delivery',
          poll_id: 'sample-dinner',
          sort_order: 3,
          description:
            'Will take like 40 minutes to get here, we can have an intermission rather than eating beforehand.',
        },
        {
          id: '6c8662c9-4ebf-ba0a-3c23-aff1c720152f',
          name: 'Just snacks',
          poll_id: 'sample-dinner',
          sort_order: 4,
          description: 'Popcorn, chips, whatever.',
        },
      ],
      confirmed: false,
      is_closed: false,
      your_name: null,
      soliciting: false,
      voted_count: 0,
      winner_name: null,
      your_scores: null,
      confirmations: [],
      winner_settled: false,
      confirmed_count: 0,
      results_available: false,
      your_confirmed_name: null,
    },
    group: [
      {
        id: 'sample-host',
        question_title: "Who's hosting?",
        question_position: 1,
      },
      {
        id: 'sample-dinner',
        question_title: 'What are we eating?',
        question_position: 2,
      },
      {
        id: 'sample-movie',
        question_title: 'What are we watching?',
        question_position: 3,
      },
    ],
  },
  'sample-result-host': {
    view: {
      poll: {
        id: 'sample-result-host',
        mode: 'open',
        title: 'Movie night',
        group_id: '7e523dbb-5277-a3f2-8787-50d8c915bb57',
        closed_at: '2026-02-13T21:37:00+00:00',
        description:
          'An example of the results from a poll. Nine people voted, and each question was harder to settle than the one before it.',
        show_voters: true,
        show_ballots: true,
        question_title: "Who's hosting?",
        solicit_options: false,
        question_position: 1,
      },
      voted: false,
      voters: ['Ana', 'Ben', 'Chloe', 'Diego', 'Erin', 'Farid', 'Gina', 'Hugo', 'Iris'],
      options: [
        {
          id: 'f3932a5d-fc0a-f630-a10e-b8d9c998eeea',
          name: "Ana's place",
          poll_id: 'sample-result-host',
          sort_order: 0,
          description: null,
        },
        {
          id: '8ba9f494-f35f-991b-5eba-425e9244c504',
          name: "Ben's loft",
          poll_id: 'sample-result-host',
          sort_order: 1,
          description: null,
        },
        {
          id: '2d668a54-9c3a-4f35-71ff-730c9ed75e0e',
          name: "Chloe's basement",
          poll_id: 'sample-result-host',
          sort_order: 2,
          description: null,
        },
      ],
      confirmed: false,
      is_closed: true,
      your_name: null,
      soliciting: false,
      voted_count: 9,
      winner_name: "Chloe's basement",
      your_scores: null,
      confirmations: [],
      winner_settled: true,
      confirmed_count: 0,
      results_available: true,
      your_confirmed_name: null,
    },
    group: [
      {
        id: 'sample-result-host',
        question_title: "Who's hosting?",
        question_position: 1,
      },
      {
        id: 'sample-result-dinner',
        question_title: 'What are we eating?',
        question_position: 2,
      },
      {
        id: 'sample-result-movie',
        question_title: 'What are we watching?',
        question_position: 3,
      },
    ],
    ballots: {
      ballots: [
        {
          voter: 'Ana',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 3,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 2,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 5,
          },
        },
        {
          voter: 'Ben',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 3,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 5,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 2,
          },
        },
        {
          voter: 'Chloe',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 5,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 1,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 2,
          },
        },
        {
          voter: 'Diego',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 5,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 2,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 3,
          },
        },
        {
          voter: 'Erin',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 4,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 1,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 4,
          },
        },
        {
          voter: 'Farid',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 5,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 3,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 2,
          },
        },
        {
          voter: 'Gina',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 4,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 2,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 3,
          },
        },
        {
          voter: 'Hugo',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 5,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 0,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 4,
          },
        },
        {
          voter: 'Iris',
          scores: {
            '2d668a54-9c3a-4f35-71ff-730c9ed75e0e': 4,
            '8ba9f494-f35f-991b-5eba-425e9244c504': 2,
            'f3932a5d-fc0a-f630-a10e-b8d9c998eeea': 1,
          },
        },
      ],
      options: [
        {
          id: 'f3932a5d-fc0a-f630-a10e-b8d9c998eeea',
          name: "Ana's place",
        },
        {
          id: '8ba9f494-f35f-991b-5eba-425e9244c504',
          name: "Ben's loft",
        },
        {
          id: '2d668a54-9c3a-4f35-71ff-730c9ed75e0e',
          name: "Chloe's basement",
        },
      ],
      voters_named: true,
    },
    ranking: [
      {
        place: 1,
        runoff: {
          ties: 1,
          prefers_a: 7,
          prefers_b: 1,
          resolved_by: 'preference',
          five_stars_a: 4,
          five_stars_b: 1,
        },
        options: [
          {
            id: '2d668a54-9c3a-4f35-71ff-730c9ed75e0e',
            name: "Chloe's basement",
            total_score: 38,
          },
        ],
        finalists: ['2d668a54-9c3a-4f35-71ff-730c9ed75e0e', 'f3932a5d-fc0a-f630-a10e-b8d9c998eeea'],
        tiebreaks: [],
      },
      {
        place: 2,
        runoff: {
          ties: 0,
          prefers_a: 6,
          prefers_b: 3,
          resolved_by: 'preference',
          five_stars_a: 1,
          five_stars_b: 1,
        },
        options: [
          {
            id: 'f3932a5d-fc0a-f630-a10e-b8d9c998eeea',
            name: "Ana's place",
            total_score: 26,
          },
        ],
        finalists: ['f3932a5d-fc0a-f630-a10e-b8d9c998eeea', '8ba9f494-f35f-991b-5eba-425e9244c504'],
        tiebreaks: [],
      },
      {
        place: 3,
        runoff: null,
        options: [
          {
            id: '8ba9f494-f35f-991b-5eba-425e9244c504',
            name: "Ben's loft",
            total_score: 18,
          },
        ],
        finalists: ['8ba9f494-f35f-991b-5eba-425e9244c504'],
        tiebreaks: [],
      },
    ],
    results: {
      tie: false,
      mode: 'open',
      runoff: {
        ties: 1,
        prefers_a: 7,
        prefers_b: 1,
        resolved_by: 'preference',
        five_stars_a: 4,
        five_stars_b: 1,
      },
      options: [
        {
          id: '2d668a54-9c3a-4f35-71ff-730c9ed75e0e',
          name: "Chloe's basement",
          description: null,
          total_score: 38,
          average_score: 4.22,
        },
        {
          id: 'f3932a5d-fc0a-f630-a10e-b8d9c998eeea',
          name: "Ana's place",
          description: null,
          total_score: 26,
          average_score: 2.89,
        },
        {
          id: '8ba9f494-f35f-991b-5eba-425e9244c504',
          name: "Ben's loft",
          description: null,
          total_score: 18,
          average_score: 2.0,
        },
      ],
      finalists: ['2d668a54-9c3a-4f35-71ff-730c9ed75e0e', 'f3932a5d-fc0a-f630-a10e-b8d9c998eeea'],
      tiebreaks: [],
      winner_id: '2d668a54-9c3a-4f35-71ff-730c9ed75e0e',
      voter_count: 9,
      closed_early: false,
      invited_count: 0,
    },
  },
  'sample-result-movie': {
    view: {
      poll: {
        id: 'sample-result-movie',
        mode: 'open',
        title: 'Movie night',
        group_id: '7e523dbb-5277-a3f2-8787-50d8c915bb57',
        closed_at: '2026-02-13T21:37:00+00:00',
        description:
          'An example of the results from a poll. Nine people voted, and each question was harder to settle than the one before it.',
        show_voters: true,
        show_ballots: true,
        question_title: 'What are we watching?',
        solicit_options: false,
        question_position: 3,
      },
      voted: false,
      voters: ['Ana', 'Ben', 'Chloe', 'Diego', 'Erin', 'Farid', 'Gina', 'Hugo', 'Iris'],
      options: [
        {
          id: '08726bf7-0f4d-190a-d5ed-c00d0565abbe',
          name: 'Knives Out',
          poll_id: 'sample-result-movie',
          sort_order: 0,
          description:
            'When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.',
        },
        {
          id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
          name: 'Spirited Away',
          poll_id: 'sample-result-movie',
          sort_order: 1,
          description:
            "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.",
        },
        {
          id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
          name: 'The Matrix',
          poll_id: 'sample-result-movie',
          sort_order: 2,
          description:
            'A computer hacker discovers that his life is nothing more than an elaborate simulation run by an evil AI.',
        },
        {
          id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
          name: 'Paddington 2',
          poll_id: 'sample-result-movie',
          sort_order: 3,
          description:
            "Paddington, now happily settled with the Brown family and a popular member of the local community, picks up a series of odd jobs to buy the perfect present for his Aunt Lucy's 100th birthday, only for the gift to be stolen.",
        },
        {
          id: 'b50cd426-947e-4697-2dbc-db6c26d1e385',
          name: 'Mean Girls',
          poll_id: 'sample-result-movie',
          sort_order: 4,
          description:
            'Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.',
        },
        {
          id: '39a0de7f-1759-b30e-263f-30c1cb117e16',
          name: 'Honeyland',
          poll_id: 'sample-result-movie',
          sort_order: 5,
          description:
            'The last female bee-hunter in Europe must save the bees and return the natural balance in Honeyland, when a family of nomadic beekeepers invade her land and threaten her livelihood.',
        },
      ],
      confirmed: false,
      is_closed: true,
      your_name: null,
      soliciting: false,
      voted_count: 9,
      winner_name: 'Knives Out',
      your_scores: null,
      confirmations: [],
      winner_settled: true,
      confirmed_count: 0,
      results_available: true,
      your_confirmed_name: null,
    },
    group: [
      {
        id: 'sample-result-host',
        question_title: "Who's hosting?",
        question_position: 1,
      },
      {
        id: 'sample-result-dinner',
        question_title: 'What are we eating?',
        question_position: 2,
      },
      {
        id: 'sample-result-movie',
        question_title: 'What are we watching?',
        question_position: 3,
      },
    ],
    ballots: {
      ballots: [
        {
          voter: 'Ana',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 5,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 3,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 4,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 0,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 2,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 1,
          },
        },
        {
          voter: 'Ben',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 4,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 5,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 3,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 1,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 2,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 1,
          },
        },
        {
          voter: 'Chloe',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 4,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 2,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 5,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 5,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 3,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 0,
          },
        },
        {
          voter: 'Diego',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 3,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 4,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 2,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 0,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 5,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 1,
          },
        },
        {
          voter: 'Erin',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 5,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 2,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 4,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 1,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 3,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 2,
          },
        },
        {
          voter: 'Farid',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 3,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 4,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 3,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 2,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 2,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 2,
          },
        },
        {
          voter: 'Gina',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 4,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 1,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 2,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 0,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 5,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 2,
          },
        },
        {
          voter: 'Hugo',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 2,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 3,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 3,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 1,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 2,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 1,
          },
        },
        {
          voter: 'Iris',
          scores: {
            '08726bf7-0f4d-190a-d5ed-c00d0565abbe': 3,
            '240967c0-62e5-88a7-a662-5dc029b84eaf': 2,
            '283438a5-4cf9-8a00-c399-cf9c72c9b2ac': 0,
            '39a0de7f-1759-b30e-263f-30c1cb117e16': 1,
            '7ddc6826-8f1e-3e14-ac34-e915a79c202e': 2,
            'b50cd426-947e-4697-2dbc-db6c26d1e385': 2,
          },
        },
      ],
      options: [
        {
          id: '08726bf7-0f4d-190a-d5ed-c00d0565abbe',
          name: 'Knives Out',
        },
        {
          id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
          name: 'Spirited Away',
        },
        {
          id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
          name: 'The Matrix',
        },
        {
          id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
          name: 'Paddington 2',
        },
        {
          id: 'b50cd426-947e-4697-2dbc-db6c26d1e385',
          name: 'Mean Girls',
        },
        {
          id: '39a0de7f-1759-b30e-263f-30c1cb117e16',
          name: 'Honeyland',
        },
      ],
      voters_named: true,
    },
    ranking: [
      {
        place: 1,
        runoff: {
          ties: 1,
          prefers_a: 6,
          prefers_b: 2,
          resolved_by: 'preference',
          five_stars_a: 2,
          five_stars_b: 1,
        },
        options: [
          {
            id: '08726bf7-0f4d-190a-d5ed-c00d0565abbe',
            name: 'Knives Out',
            total_score: 33,
          },
        ],
        finalists: ['08726bf7-0f4d-190a-d5ed-c00d0565abbe', '283438a5-4cf9-8a00-c399-cf9c72c9b2ac'],
        tiebreaks: [
          {
            tied: [
              {
                id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                name: 'Paddington 2',
                total_score: 26,
              },
              {
                id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                name: 'Spirited Away',
                total_score: 26,
              },
              {
                id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                name: 'The Matrix',
                total_score: 26,
              },
            ],
            slots: 1,
            steps: [
              {
                rule: 'head_to_head',
                results: [
                  {
                    id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    name: 'Spirited Away',
                    value: 1,
                  },
                  {
                    id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    name: 'Paddington 2',
                    value: 0,
                  },
                  {
                    id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    name: 'The Matrix',
                    value: 0,
                  },
                ],
                decisive: true,
                matchups: [
                  {
                    a: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    b: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    ties: 0,
                    a_name: 'Paddington 2',
                    b_name: 'Spirited Away',
                    prefers_a: 3,
                    prefers_b: 6,
                  },
                  {
                    a: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    b: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    ties: 1,
                    a_name: 'Paddington 2',
                    b_name: 'The Matrix',
                    prefers_a: 4,
                    prefers_b: 4,
                  },
                  {
                    a: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    b: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    ties: 1,
                    a_name: 'Spirited Away',
                    b_name: 'The Matrix',
                    prefers_a: 4,
                    prefers_b: 4,
                  },
                ],
              },
            ],
            tied_at: 26,
            advanced: [
              {
                id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                name: 'Spirited Away',
              },
            ],
            resolved_by: 'head_to_head',
          },
        ],
      },
      {
        place: 2,
        runoff: {
          ties: 0,
          prefers_a: 6,
          prefers_b: 3,
          resolved_by: 'preference',
          five_stars_a: 1,
          five_stars_b: 2,
        },
        options: [
          {
            id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
            name: 'Spirited Away',
            total_score: 26,
          },
        ],
        finalists: ['283438a5-4cf9-8a00-c399-cf9c72c9b2ac', '7ddc6826-8f1e-3e14-ac34-e915a79c202e'],
        tiebreaks: [
          {
            tied: [
              {
                id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                name: 'Paddington 2',
                total_score: 26,
              },
              {
                id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                name: 'Spirited Away',
                total_score: 26,
              },
              {
                id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                name: 'The Matrix',
                total_score: 26,
              },
            ],
            slots: 2,
            steps: [
              {
                rule: 'head_to_head',
                results: [
                  {
                    id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    name: 'Spirited Away',
                    value: 1,
                  },
                  {
                    id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    name: 'Paddington 2',
                    value: 0,
                  },
                  {
                    id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    name: 'The Matrix',
                    value: 0,
                  },
                ],
                decisive: false,
                matchups: [
                  {
                    a: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    b: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    ties: 0,
                    a_name: 'Paddington 2',
                    b_name: 'Spirited Away',
                    prefers_a: 3,
                    prefers_b: 6,
                  },
                  {
                    a: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    b: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    ties: 1,
                    a_name: 'Paddington 2',
                    b_name: 'The Matrix',
                    prefers_a: 4,
                    prefers_b: 4,
                  },
                  {
                    a: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    b: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    ties: 1,
                    a_name: 'Spirited Away',
                    b_name: 'The Matrix',
                    prefers_a: 4,
                    prefers_b: 4,
                  },
                ],
              },
              {
                rule: 'five_star_votes',
                results: [
                  {
                    id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                    name: 'Paddington 2',
                    value: 2,
                  },
                  {
                    id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                    name: 'Spirited Away',
                    value: 1,
                  },
                  {
                    id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                    name: 'The Matrix',
                    value: 1,
                  },
                ],
                decisive: true,
              },
            ],
            tied_at: 26,
            advanced: [
              {
                id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                name: 'Spirited Away',
              },
              {
                id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                name: 'Paddington 2',
              },
            ],
            resolved_by: 'five_star_votes',
          },
        ],
      },
      {
        place: 3,
        runoff: {
          ties: 1,
          prefers_a: 4,
          prefers_b: 4,
          resolved_by: 'five_star_votes',
          five_stars_a: 1,
          five_stars_b: 2,
        },
        options: [
          {
            id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
            name: 'Paddington 2',
            total_score: 26,
          },
        ],
        finalists: ['240967c0-62e5-88a7-a662-5dc029b84eaf', '7ddc6826-8f1e-3e14-ac34-e915a79c202e'],
        tiebreaks: [],
      },
      {
        place: 4,
        runoff: {
          ties: 2,
          prefers_a: 6,
          prefers_b: 1,
          resolved_by: 'preference',
          five_stars_a: 1,
          five_stars_b: 0,
        },
        options: [
          {
            id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
            name: 'The Matrix',
            total_score: 26,
          },
        ],
        finalists: ['240967c0-62e5-88a7-a662-5dc029b84eaf', 'b50cd426-947e-4697-2dbc-db6c26d1e385'],
        tiebreaks: [],
      },
      {
        place: 5,
        runoff: {
          ties: 3,
          prefers_a: 5,
          prefers_b: 1,
          resolved_by: 'preference',
          five_stars_a: 0,
          five_stars_b: 1,
        },
        options: [
          {
            id: 'b50cd426-947e-4697-2dbc-db6c26d1e385',
            name: 'Mean Girls',
            total_score: 12,
          },
        ],
        finalists: ['b50cd426-947e-4697-2dbc-db6c26d1e385', '39a0de7f-1759-b30e-263f-30c1cb117e16'],
        tiebreaks: [],
      },
      {
        place: 6,
        runoff: null,
        options: [
          {
            id: '39a0de7f-1759-b30e-263f-30c1cb117e16',
            name: 'Honeyland',
            total_score: 11,
          },
        ],
        finalists: ['39a0de7f-1759-b30e-263f-30c1cb117e16'],
        tiebreaks: [],
      },
    ],
    results: {
      tie: true,
      mode: 'open',
      runoff: {
        ties: 1,
        prefers_a: 6,
        prefers_b: 2,
        resolved_by: 'preference',
        five_stars_a: 2,
        five_stars_b: 1,
      },
      options: [
        {
          id: '08726bf7-0f4d-190a-d5ed-c00d0565abbe',
          name: 'Knives Out',
          description:
            'When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.',
          total_score: 33,
          average_score: 3.67,
        },
        {
          id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
          name: 'Spirited Away',
          description:
            "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.",
          total_score: 26,
          average_score: 2.89,
        },
        {
          id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
          name: 'Paddington 2',
          description:
            "Paddington, now happily settled with the Brown family and a popular member of the local community, picks up a series of odd jobs to buy the perfect present for his Aunt Lucy's 100th birthday, only for the gift to be stolen.",
          total_score: 26,
          average_score: 2.89,
        },
        {
          id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
          name: 'The Matrix',
          description:
            'A computer hacker discovers that his life is nothing more than an elaborate simulation run by an evil AI.',
          total_score: 26,
          average_score: 2.89,
        },
        {
          id: 'b50cd426-947e-4697-2dbc-db6c26d1e385',
          name: 'Mean Girls',
          description:
            'Cady Heron is a hit with The Plastics, the A-list girl clique at her new school, until she makes the mistake of falling for Aaron Samuels, the ex-boyfriend of alpha Plastic Regina George.',
          total_score: 12,
          average_score: 1.33,
        },
        {
          id: '39a0de7f-1759-b30e-263f-30c1cb117e16',
          name: 'Honeyland',
          description:
            'The last female bee-hunter in Europe must save the bees and return the natural balance in Honeyland, when a family of nomadic beekeepers invade her land and threaten her livelihood.',
          total_score: 11,
          average_score: 1.22,
        },
      ],
      finalists: ['08726bf7-0f4d-190a-d5ed-c00d0565abbe', '283438a5-4cf9-8a00-c399-cf9c72c9b2ac'],
      tiebreaks: [
        {
          tied: [
            {
              id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
              name: 'Paddington 2',
              total_score: 26,
            },
            {
              id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
              name: 'Spirited Away',
              total_score: 26,
            },
            {
              id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
              name: 'The Matrix',
              total_score: 26,
            },
          ],
          slots: 1,
          steps: [
            {
              rule: 'head_to_head',
              results: [
                {
                  id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                  name: 'Spirited Away',
                  value: 1,
                },
                {
                  id: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                  name: 'Paddington 2',
                  value: 0,
                },
                {
                  id: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                  name: 'The Matrix',
                  value: 0,
                },
              ],
              decisive: true,
              matchups: [
                {
                  a: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                  b: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                  ties: 0,
                  a_name: 'Paddington 2',
                  b_name: 'Spirited Away',
                  prefers_a: 3,
                  prefers_b: 6,
                },
                {
                  a: '7ddc6826-8f1e-3e14-ac34-e915a79c202e',
                  b: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                  ties: 1,
                  a_name: 'Paddington 2',
                  b_name: 'The Matrix',
                  prefers_a: 4,
                  prefers_b: 4,
                },
                {
                  a: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
                  b: '240967c0-62e5-88a7-a662-5dc029b84eaf',
                  ties: 1,
                  a_name: 'Spirited Away',
                  b_name: 'The Matrix',
                  prefers_a: 4,
                  prefers_b: 4,
                },
              ],
            },
          ],
          tied_at: 26,
          advanced: [
            {
              id: '283438a5-4cf9-8a00-c399-cf9c72c9b2ac',
              name: 'Spirited Away',
            },
          ],
          resolved_by: 'head_to_head',
        },
      ],
      winner_id: '08726bf7-0f4d-190a-d5ed-c00d0565abbe',
      voter_count: 9,
      closed_early: false,
      invited_count: 0,
    },
  },
  'sample-result-dinner': {
    view: {
      poll: {
        id: 'sample-result-dinner',
        mode: 'open',
        title: 'Movie night',
        group_id: '7e523dbb-5277-a3f2-8787-50d8c915bb57',
        closed_at: '2026-02-13T21:37:00+00:00',
        description:
          'An example of the results from a poll. Nine people voted, and each question was harder to settle than the one before it.',
        show_voters: true,
        show_ballots: true,
        question_title: 'What are we eating?',
        solicit_options: false,
        question_position: 2,
      },
      voted: false,
      voters: ['Ana', 'Ben', 'Chloe', 'Diego', 'Erin', 'Farid', 'Gina', 'Hugo', 'Iris'],
      options: [
        {
          id: '366ce86b-5939-fbb4-8407-df63fd2c4aca',
          name: 'Two big pizzas',
          poll_id: 'sample-result-dinner',
          sort_order: 0,
          description: 'One pepperoni, one cheese.',
        },
        {
          id: 'd14066b2-1042-18f5-9a47-ce68843ef18c',
          name: 'Taco bar',
          poll_id: 'sample-result-dinner',
          sort_order: 1,
          description: 'Build your own tacos!',
        },
        {
          id: 'b5b174ab-85ae-0fe4-da06-05c3e04186e0',
          name: 'Everyone brings a dish',
          poll_id: 'sample-result-dinner',
          sort_order: 2,
          description: null,
        },
        {
          id: '33b51896-f06b-3ce0-c3e8-6299859b60ce',
          name: 'Thai delivery',
          poll_id: 'sample-result-dinner',
          sort_order: 3,
          description:
            'Will take like 40 minutes to get here, we can have an intermission rather than eating beforehand.',
        },
        {
          id: '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b',
          name: 'Just snacks',
          poll_id: 'sample-result-dinner',
          sort_order: 4,
          description: 'Popcorn, chips, whatever.',
        },
      ],
      confirmed: false,
      is_closed: true,
      your_name: null,
      soliciting: false,
      voted_count: 9,
      winner_name: 'Two big pizzas',
      your_scores: null,
      confirmations: [],
      winner_settled: true,
      confirmed_count: 0,
      results_available: true,
      your_confirmed_name: null,
    },
    group: [
      {
        id: 'sample-result-host',
        question_title: "Who's hosting?",
        question_position: 1,
      },
      {
        id: 'sample-result-dinner',
        question_title: 'What are we eating?',
        question_position: 2,
      },
      {
        id: 'sample-result-movie',
        question_title: 'What are we watching?',
        question_position: 3,
      },
    ],
    ballots: {
      ballots: [
        {
          voter: 'Ana',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 3,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 1,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 2,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 5,
          },
        },
        {
          voter: 'Ben',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 0,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 2,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 2,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 1,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 5,
          },
        },
        {
          voter: 'Chloe',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 2,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 3,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 3,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 5,
          },
        },
        {
          voter: 'Diego',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 2,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 1,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 2,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 2,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 5,
          },
        },
        {
          voter: 'Erin',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 3,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 4,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 2,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 3,
          },
        },
        {
          voter: 'Farid',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 4,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 5,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 1,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 2,
          },
        },
        {
          voter: 'Gina',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 2,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 5,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 3,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 4,
          },
        },
        {
          voter: 'Hugo',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 2,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 4,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 2,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 3,
          },
        },
        {
          voter: 'Iris',
          scores: {
            '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b': 1,
            '33b51896-f06b-3ce0-c3e8-6299859b60ce': 3,
            '366ce86b-5939-fbb4-8407-df63fd2c4aca': 4,
            'b5b174ab-85ae-0fe4-da06-05c3e04186e0': 2,
            'd14066b2-1042-18f5-9a47-ce68843ef18c': 3,
          },
        },
      ],
      options: [
        {
          id: '366ce86b-5939-fbb4-8407-df63fd2c4aca',
          name: 'Two big pizzas',
        },
        {
          id: 'd14066b2-1042-18f5-9a47-ce68843ef18c',
          name: 'Taco bar',
        },
        {
          id: 'b5b174ab-85ae-0fe4-da06-05c3e04186e0',
          name: 'Everyone brings a dish',
        },
        {
          id: '33b51896-f06b-3ce0-c3e8-6299859b60ce',
          name: 'Thai delivery',
        },
        {
          id: '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b',
          name: 'Just snacks',
        },
      ],
      voters_named: true,
    },
    ranking: [
      {
        place: 1,
        runoff: {
          ties: 0,
          prefers_a: 4,
          prefers_b: 5,
          resolved_by: 'preference',
          five_stars_a: 4,
          five_stars_b: 2,
        },
        options: [
          {
            id: '366ce86b-5939-fbb4-8407-df63fd2c4aca',
            name: 'Two big pizzas',
            total_score: 30,
          },
        ],
        finalists: ['d14066b2-1042-18f5-9a47-ce68843ef18c', '366ce86b-5939-fbb4-8407-df63fd2c4aca'],
        tiebreaks: [],
      },
      {
        place: 2,
        runoff: {
          ties: 2,
          prefers_a: 6,
          prefers_b: 1,
          resolved_by: 'preference',
          five_stars_a: 4,
          five_stars_b: 0,
        },
        options: [
          {
            id: 'd14066b2-1042-18f5-9a47-ce68843ef18c',
            name: 'Taco bar',
            total_score: 35,
          },
        ],
        finalists: ['d14066b2-1042-18f5-9a47-ce68843ef18c', '33b51896-f06b-3ce0-c3e8-6299859b60ce'],
        tiebreaks: [],
      },
      {
        place: 3,
        runoff: {
          ties: 1,
          prefers_a: 5,
          prefers_b: 3,
          resolved_by: 'preference',
          five_stars_a: 0,
          five_stars_b: 0,
        },
        options: [
          {
            id: '33b51896-f06b-3ce0-c3e8-6299859b60ce',
            name: 'Thai delivery',
            total_score: 22,
          },
        ],
        finalists: ['33b51896-f06b-3ce0-c3e8-6299859b60ce', 'b5b174ab-85ae-0fe4-da06-05c3e04186e0'],
        tiebreaks: [],
      },
      {
        place: 4,
        runoff: {
          ties: 2,
          prefers_a: 7,
          prefers_b: 0,
          resolved_by: 'preference',
          five_stars_a: 0,
          five_stars_b: 0,
        },
        options: [
          {
            id: 'b5b174ab-85ae-0fe4-da06-05c3e04186e0',
            name: 'Everyone brings a dish',
            total_score: 18,
          },
        ],
        finalists: ['b5b174ab-85ae-0fe4-da06-05c3e04186e0', '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b'],
        tiebreaks: [],
      },
      {
        place: 5,
        runoff: null,
        options: [
          {
            id: '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b',
            name: 'Just snacks',
            total_score: 9,
          },
        ],
        finalists: ['2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b'],
        tiebreaks: [],
      },
    ],
    results: {
      tie: false,
      mode: 'open',
      runoff: {
        ties: 0,
        prefers_a: 4,
        prefers_b: 5,
        resolved_by: 'preference',
        five_stars_a: 4,
        five_stars_b: 2,
      },
      options: [
        {
          id: 'd14066b2-1042-18f5-9a47-ce68843ef18c',
          name: 'Taco bar',
          description: 'Build your own tacos!',
          total_score: 35,
          average_score: 3.89,
        },
        {
          id: '366ce86b-5939-fbb4-8407-df63fd2c4aca',
          name: 'Two big pizzas',
          description: 'One pepperoni, one cheese.',
          total_score: 30,
          average_score: 3.33,
        },
        {
          id: '33b51896-f06b-3ce0-c3e8-6299859b60ce',
          name: 'Thai delivery',
          description:
            'Will take like 40 minutes to get here, we can have an intermission rather than eating beforehand.',
          total_score: 22,
          average_score: 2.44,
        },
        {
          id: 'b5b174ab-85ae-0fe4-da06-05c3e04186e0',
          name: 'Everyone brings a dish',
          description: null,
          total_score: 18,
          average_score: 2.0,
        },
        {
          id: '2695ffa3-1c9b-5f6f-c9b7-1df3e6a6457b',
          name: 'Just snacks',
          description: 'Popcorn, chips, whatever.',
          total_score: 9,
          average_score: 1.0,
        },
      ],
      finalists: ['d14066b2-1042-18f5-9a47-ce68843ef18c', '366ce86b-5939-fbb4-8407-df63fd2c4aca'],
      tiebreaks: [],
      winner_id: '366ce86b-5939-fbb4-8407-df63fd2c4aca',
      voter_count: 9,
      closed_early: false,
      invited_count: 0,
    },
  },
}
