#!/usr/bin/env bash
#
# Regenerates the About page's sample poll.
#
#   scripts/sample-poll.sh
#
# Builds a throwaway database from the migrations, creates the sample poll in
# it through the app's own write path, casts the ballots, closes it, and writes
# what the public voting page's RPCs answer into
# src/lib/samplePollData.ts. The browser serves the sample from that file: no
# sample rows live in the real database, where the nightly retention purge
# would eventually delete them and where a stray vote would change the tally
# the About page promises.
#
# Needs a Postgres server, like the tests do. See scripts/sample-poll.sql for
# the poll itself; edit the ballots there and rerun this.

set -euo pipefail

cd "$(dirname "$0")/.."

DB="${SAMPLE_DB:-star_voting_sample}"
OUT="src/lib/samplePollData.ts"

red()  { printf '\033[31m%s\033[0m\n' "$1"; }
bold() { printf '\033[1m%s\033[0m\n' "$1"; }

bold "Building $DB from supabase/migrations ..."
test/build-db.sh "$DB"

# tests.sign_in() is what puts a creator behind create_poll_group() and
# close_poll(), which is the same thing the tally suite needs it for.
psql -v ON_ERROR_STOP=1 -q -d "$DB" -f test/sql/helpers.sql

bold "Casting the sample ballots ..."
payload="$(psql -v ON_ERROR_STOP=1 -q -X -d "$DB" -f scripts/sample-poll.sql)"

if [[ -z "$payload" ]]; then
  red "The generator produced nothing; $OUT is unchanged."
  exit 1
fi

{
  cat <<'HEADER'
/**
 * Generated by scripts/sample-poll.sh. Do not edit by hand: change the poll
 * or its ballots in scripts/sample-poll.sql and run that script again.
 *
 * What the public voting page's RPCs answer about the About page's sample
 * poll, recorded against a throwaway database built from the migrations. The
 * tally, the tie-breaks and the full ranking in here are the ones
 * `star_round()` and `poll_ranking()` produced from the ballots in that file;
 * nothing in the browser recomputes them.
 */
import type { SamplePayloads } from './samplePoll'

export const SAMPLE_PAYLOADS: SamplePayloads =
HEADER
  printf '%s' "$payload"
  printf '\n'
} > "$OUT"

npx oxfmt "$OUT" >/dev/null

bold "Wrote $OUT ($(wc -l < "$OUT") lines)."
