#!/usr/bin/env bash
#
# Squashes the migrations, then puts back what the squash cannot carry.
#
#   scripts/squash.sh
#
# Use this instead of calling `supabase migration squash` directly. The squash
# replays the migrations into a shadow database and pg_dumps the result, so
# only schema survives it -- the DO blocks that schedule the nightly purge are
# not schema, and a plain squash drops them silently. This script runs the
# squash and then replays supabase/after-squash.sql into a fresh migration on
# top of the new baseline.
#
# Commit the result on its own, with no other changes, so the replacement is
# easy to review.

set -euo pipefail

cd "$(dirname "$0")/.."

MIGRATIONS_DIR="supabase/migrations"
AFTER_SQUASH="supabase/after-squash.sql"

red()  { printf '\033[31m%s\033[0m\n' "$1"; }
bold() { printf '\033[1m%s\033[0m\n' "$1"; }

[[ -f "$AFTER_SQUASH" ]] || { red "No $AFTER_SQUASH to replay."; exit 1; }

# The squash rewrites the newest migration in place and deletes the rest, so
# the state before it is worth being able to get back to.
before="$(ls "$MIGRATIONS_DIR"/*.sql 2>/dev/null | wc -l)"
if [[ -n "$(git status --porcelain -- "$MIGRATIONS_DIR")" ]]; then
  red "$MIGRATIONS_DIR has uncommitted changes; commit or stash them first."
  red "The squash rewrites these files, and git is the only way back."
  exit 1
fi

bold "Squashing $before migrations ..."
npx supabase migration squash --linked

# Every squash so far has collapsed everything into the newest file, keeping
# that file's name. Assert it rather than assume it: if a future CLI writes a
# differently named or additional file, stopping here is far better than
# numbering the replay against a directory that is not what we think it is.
mapfile -t remaining < <(ls "$MIGRATIONS_DIR"/*.sql 2>/dev/null)
if [[ "${#remaining[@]}" -ne 1 ]]; then
  red "Expected the squash to leave exactly one migration, found ${#remaining[@]}:"
  printf '  %s\n' "${remaining[@]}"
  red "Nothing has been replayed. Check the directory before committing."
  exit 1
fi

baseline="${remaining[0]}"
version="$(basename "$baseline" | cut -d_ -f1)"
if ! [[ "$version" =~ ^[0-9]+$ ]]; then
  red "Cannot read a version number from $(basename "$baseline")."
  exit 1
fi

# The baseline inherits the name of whatever migration it overwrote, which
# after the first run of this script is the replay from the previous one --
# a file called "..._scheduled_jobs.sql" holding the entire schema. Renaming
# keeps the version prefix, which is the part Supabase's migration history is
# keyed on; only the label after it changes.
if [[ "$(basename "$baseline")" != "${version}_baseline.sql" ]]; then
  git mv "$baseline" "$MIGRATIONS_DIR/${version}_baseline.sql"
  baseline="$MIGRATIONS_DIR/${version}_baseline.sql"
  echo "Renamed the baseline to $(basename "$baseline") (version $version is unchanged)."
fi

# The replay is a new migration, not an append to the baseline: `--linked` has
# already marked the baseline as applied on the live project, so anything
# added to that file would never run there. A new version is picked up by the
# GitHub integration on merge like any other, which also means a live database
# that somehow lost the job gets it back.
next="$(printf '%0*d' "${#version}" "$((10#$version + 1))")"
replay="$MIGRATIONS_DIR/${next}_scheduled_jobs.sql"

{
  echo "-- Generated by scripts/squash.sh from $AFTER_SQUASH. Do not edit this"
  echo "-- file: the next squash deletes it, and the script writes it out again"
  echo "-- from that source. Change $AFTER_SQUASH instead."
  echo
  cat "$AFTER_SQUASH"
} > "$replay"

echo "Replayed $AFTER_SQUASH into $(basename "$replay")."
echo

bold "Checking the result ..."
npm test

echo
bold "Local and remote migration history:"
npx supabase migration list --linked || true

echo
bold "Now review and commit:"
echo "  git add -A $MIGRATIONS_DIR"
echo "  git commit -m 'Squashing migrations'"
